#include "kernel-hdr/host1x.h"

#define MAKE_CONST(req_name) const __u64 MK_##req_name = req_name;

MAKE_CONST(HOST1X_IOCTL_ALLOCATE_SYNCPOINT)
MAKE_CONST(HOST1X_IOCTL_READ_SYNCPOINT)
MAKE_CONST(HOST1X_IOCTL_CREATE_FENCE)
MAKE_CONST(HOST1X_IOCTL_FENCE_EXTRACT)
MAKE_CONST(HOST1X_IOCTL_SYNCPOINT_INFO)
MAKE_CONST(HOST1X_IOCTL_SYNCPOINT_INCREMENT)
